name: .NET Core CI

on:
  push:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'
  workflow_dispatch:

jobs:
  build:
    name: .NET on ${{ matrix.runs-on }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, windows-latest]
        configuration: [Release]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5

      - name: Build
        run: dotnet publish DepotDownloader/DepotDownloader.csproj -c ${{ matrix.configuration }} -o artifacts /p:ContinuousIntegrationBuild=true

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        if: matrix.configuration == 'Release' && matrix.runs-on == 'windows-latest'
        with:
          name: DepotDownloader-framework
          path: artifacts
          if-no-files-found: error

      - name: Publish Windows-x64
        if: matrix.configuration == 'Release' && matrix.runs-on == 'windows-latest'
        run: dotnet publish DepotDownloader/DepotDownloader.csproj --configuration Release -p:PublishSingleFile=true -p:PublishTrimmed=true -p:EnableCompressionInSingleFile=true -p:DebugType=None -p:DebugSymbols=false --self-contained --runtime win-x64 --output selfcontained-win-x64

      - name: Publish Linux-x64
        if: matrix.configuration == 'Release' && matrix.runs-on == 'ubuntu-latest'
        run: dotnet publish DepotDownloader/DepotDownloader.csproj --configuration Release -p:PublishSingleFile=true -p:PublishTrimmed=true -p:EnableCompressionInSingleFile=true -p:DebugType=None -p:DebugSymbols=false --self-contained --runtime linux-x64 --output selfcontained-linux-x64

      - name: Upload Windows-x64
        uses: actions/upload-artifact@v7
        if: matrix.configuration == 'Release' && matrix.runs-on == 'windows-latest'
        with:
          name: DepotDownloader-windows-x64
          path: selfcontained-win-x64
          if-no-files-found: error

      - name: Upload Linux-x64
        uses: actions/upload-artifact@v7
        if: matrix.configuration == 'Release' && matrix.runs-on == 'ubuntu-latest'
        with:
          name: DepotDownloader-linux-x64
          path: selfcontained-linux-x64
          if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        path: artifacts

    - name: Display artifacts folder structure
      run: ls -Rl
      working-directory: artifacts

    - name: Create release files
      run: |
        set -eux
        mkdir release
        chmod +x artifacts/DepotDownloader-linux-x64/DepotDownloader
        zip -9j release/DepotDownloader-framework.zip artifacts/DepotDownloader-framework/*
        zip -9j release/DepotDownloader-windows-x64.zip artifacts/DepotDownloader-windows-x64/*
        zip -9j release/DepotDownloader-linux-x64.zip artifacts/DepotDownloader-linux-x64/*

    - name: Display structure of archived files
      run: ls -Rl
      working-directory: release

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
